arb-dir: lib/l10n
output-dir: lib/l10n/generated
untranslated-messages-file: lib/l10n/missing_localizations.json
template-arb-file: fitness_en.arb
output-localization-file: fitness_localizations.dart
output-class: FitnessLocalizations
preferred-supported-locales: "en"
synthetic-package: false
use-deferred-loading: false