name: fitness_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   


  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.7.0
  flutter_svg: ^2.0.1
  intl: ^0.17.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  hive: ^2.2.3
  recase: ^4.1.0
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
